spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/giftshop
    username: giftshop
    password: giftshop
  flyway:
    enabled: true
    url: jdbc:mariadb://127.0.0.1:3306/giftshop
    user: giftshop
    password: giftshop
    table: schema_version
  application:
    name: giftshop
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: example
      authentication-database: admin
